<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Films.Data/Films.Data.csproj" />
    <ProjectReference Include="../Films.Entities/Films.Entities.csproj" />
  </ItemGroup>

</Project>
