[tool.poetry]
name = "api"
version = "0.0.1"
description = "We will start create api"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
fastapi = "^0.133.0"
uvicorn = "^0.41.0"
ruff = "^0.15.4"

[tool.poetry.group.dev.dependencies]
black = "^26.1.0"
ruff = "^0.15.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "D", "F"]
